ARG SINGBOX_IMAGE
FROM ${SINGBOX_IMAGE} AS sing-box

FROM golang:1.26-bookworm AS controller-build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY cmd/ ./cmd/
COPY internal/ ./internal/
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /out/core-controller ./cmd/core-controller

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=controller-build /out/core-controller /usr/local/bin/core-controller
COPY --from=sing-box /usr/local/bin/sing-box /usr/local/bin/sing-box
USER nonroot:nonroot
ENTRYPOINT ["/usr/local/bin/core-controller"]
